int handleSigInt();
int handleSigStop();
int hasActiveJob();
int lastExitStatus();
void printBackgroundJobs();
void initJobs();
void createNewProcess(char* command, char **args, char* input, int redirectStatus,char* redirectFile,int sendToBackground);
void killAllProcesses();
int continueJob(int job);
int continueJobFg(int job);